---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-auth
  labels:
    app: mall-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-auth
  template:
    metadata:
      labels:
        app: mall-auth
    spec:
      containers:
        - name: mall-auth
          # 指定Docker Hub中的镜像地址
          image: ikubernetes/mall-auth:1.0-SNAPSHOT
          ports:
            - containerPort: 8401
          env:
            # 指定环境
            - name: spring.profiles.active
              value: prod
            # 指定时区
            - name: TZ
              value: Asia/Shanghai
            # 指定Nacos地址
            - name: spring.cloud.nacos.discovery.server-addr
              value: http://nacos.nacos.svc:8848
            - name: spring.cloud.nacos.config.server-addr
              value: http://nacos.nacos.svc:8848
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/skywalking/agent/skywalking-agent.jar"
            - name: SW_AGENT_NAME
              value: "mall-auth"
            - name: SW_AGENT_NAMESPACE
              value: "mall"
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "skywalking-oap.tracing.svc:11800"
          volumeMounts:
          - mountPath: /skywalking
            name: skywalking-agent
      initContainers:
        - name: sw-agent
          #image: registry.magedu.com/apache/skywalking-java-agent:9.0.0-java8
          image: apache/skywalking-java-agent:9.0.0-java8
          volumeMounts:
            - name: skywalking-agent
              mountPath: /data
          command: [ "/bin/sh" ]
          args: [ "-c", "cp -R /skywalking/agent /data/" ]
      volumes:
        - name: skywalking-agent
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mall-auth
spec:
  type: ClusterIP
  selector:
    app: mall-auth
  ports:
    - name: http
      protocol: TCP
      port: 8401
      targetPort: 8401
