apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-restore
spec:
  dataSource:
    name: nfs-pvc-snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
