apiVersion: v1
kind: Secret
metadata:
  name: gitlab
data:
  db_pass: bWFnZWR1LmNvbQ==
  db_user: Z2l0bGFi
  db_name: Z2l0bGFiX3Byb2R1Y3Rpb24=
  imap_user: TWFnZUVkdQ==
  imap_pass: bWFnZWR1LmNvbQ==
  # imap password: magedu.com
  smtp_user: bWFpbGVyQG1hZ2VkdS5jb20=
  smtp_pass: bWFnZWR1LmNvbQ==
  # smtp password: magedu.com
type: Opaque
