apiVersion: v1
kind: Pod
metadata:
  labels:
    run: projected-demo
  name: projected-demo
spec:
  containers:
  - image: ikubernetes/demoapp:v1.0
    name: projected-demo
    volumeMounts:
    - name: proj
      mountPath: /proj
  volumes:
  - name: proj
    projected:
      defaultMode: 0644
      sources:
      - configMap:
          items:
          - key: myserver.conf
            path: my.conf
          name: nginx-config-files
      - secret:
          items:
          - key: tls.crt
            path: nginx.crt
          name: nginx-ssl-secret
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace 
