apiVersion: v1
kind: Service
metadata:
  name: nacos
  labels:
    app: nacos 
  annotations: {}
    #prometheus.io/scrape: "true"
    #prometheus.io/port: "8848"
    #prometheus.io/path: "/nacos/actuator/prometheus"  
spec:
  #type: LoadBalancer
  ports:
    - port: 8848
      name: server
      targetPort: 8848
  selector:
    app: nacos
