version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2024-02-26T09-33-48Z
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'magedu.com'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - minionetwork
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    command: server /data 
    #command: server --console-address ":9001" /data 

networks:
  minionetwork:
    driver: bridge
