# Maintainer: MageEdu <mage@magedu.com>
# Site: http://www.magedu.com
#
---
kind: Secret
apiVersion: v1
metadata:
  name: redis-secret
type: Opaque
data:
  REDIS_PASSWORD: "bWFnZWR1LmNvbQ=="
  #REDIS_PASSWORD: "magedu.com"
